services:
  hugo:
    image: hugomods/hugo:exts
    container_name: hugo_server
    working_dir: /src                  # project is mounted here
    volumes:
      - ./:/src
    ports:
      - "1313:1313"                    # host → container
    command: >
      server
      --bind=0.0.0.0
      --disableFastRender
      --poll=700ms
      -D
